swagger: '2.0'
info:
  version: '1.0.0'
  title: MindsLab Rest API documentation
  description: Swagger documentation for the Gorilla table backend project APIs
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: abdelouahedelhariri@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 18.222.111.108
basePath: /api/v1
schemes:
  - http
paths:                  
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization 
        in: header
definitions: